// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1common "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

type TLSSettingInitParameters struct {

	// (String) The hostname for which the tls settings are set.
	// The hostname for which the tls settings are set.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	// The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	SettingID *string `json:"settingId,omitempty" tf:"setting_id,omitempty"`

	// (Dynamic) The tls setting value.
	// The tls setting value.
	Value *v1.JSON `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier.
	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type TLSSettingObservation struct {

	// (String) This is the time the tls setting was originally created for this hostname.
	// This is the time the tls setting was originally created for this hostname.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The hostname for which the tls settings are set.
	// The hostname for which the tls settings are set.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	// The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	SettingID *string `json:"settingId,omitempty" tf:"setting_id,omitempty"`

	// (String) Deployment status for the given tls setting.
	// Deployment status for the given tls setting.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) This is the time the tls setting was updated.
	// This is the time the tls setting was updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (Dynamic) The tls setting value.
	// The tls setting value.
	Value *v1.JSON `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier.
	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type TLSSettingParameters struct {

	// (String) The hostname for which the tls settings are set.
	// The hostname for which the tls settings are set.
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	// The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	// +kubebuilder:validation:Optional
	SettingID *string `json:"settingId,omitempty" tf:"setting_id,omitempty"`

	// (Dynamic) The tls setting value.
	// The tls setting value.
	// +kubebuilder:validation:Optional
	Value *v1.JSON `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

// TLSSettingSpec defines the desired state of TLSSetting
type TLSSettingSpec struct {
	v1common.ResourceSpec `json:",inline"`
	ForProvider           TLSSettingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TLSSettingInitParameters `json:"initProvider,omitempty"`
}

// TLSSettingStatus defines the observed state of TLSSetting.
type TLSSettingStatus struct {
	v1common.ResourceStatus `json:",inline"`
	AtProvider              TLSSettingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TLSSetting is the Schema for the TLSSettings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type TLSSetting struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostname) || (has(self.initProvider) && has(self.initProvider.hostname))",message="spec.forProvider.hostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settingId) || (has(self.initProvider) && has(self.initProvider.settingId))",message="spec.forProvider.settingId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneId) || (has(self.initProvider) && has(self.initProvider.zoneId))",message="spec.forProvider.zoneId is a required parameter"
	Spec   TLSSettingSpec   `json:"spec"`
	Status TLSSettingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TLSSettingList contains a list of TLSSettings
type TLSSettingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TLSSetting `json:"items"`
}

// Repository type metadata.
var (
	TLSSetting_Kind             = "TLSSetting"
	TLSSetting_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TLSSetting_Kind}.String()
	TLSSetting_KindAPIVersion   = TLSSetting_Kind + "." + CRDGroupVersion.String()
	TLSSetting_GroupVersionKind = CRDGroupVersion.WithKind(TLSSetting_Kind)
)

func init() {
	SchemeBuilder.Register(&TLSSetting{}, &TLSSettingList{})
}
