// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/prolixalias/provider-cloudflare/apis/namespaced/access/v1alpha1"
	v1alpha1account "github.com/prolixalias/provider-cloudflare/apis/namespaced/account/v1alpha1"
	v1alpha1addressmap "github.com/prolixalias/provider-cloudflare/apis/namespaced/addressmap/v1alpha1"
	v1alpha1api "github.com/prolixalias/provider-cloudflare/apis/namespaced/api/v1alpha1"
	v1alpha1argo "github.com/prolixalias/provider-cloudflare/apis/namespaced/argo/v1alpha1"
	v1alpha1authenticated "github.com/prolixalias/provider-cloudflare/apis/namespaced/authenticated/v1alpha1"
	v1alpha1bot "github.com/prolixalias/provider-cloudflare/apis/namespaced/bot/v1alpha1"
	v1alpha1byo "github.com/prolixalias/provider-cloudflare/apis/namespaced/byo/v1alpha1"
	v1alpha1calls "github.com/prolixalias/provider-cloudflare/apis/namespaced/calls/v1alpha1"
	v1alpha1certificate "github.com/prolixalias/provider-cloudflare/apis/namespaced/certificate/v1alpha1"
	v1alpha1cloud "github.com/prolixalias/provider-cloudflare/apis/namespaced/cloud/v1alpha1"
	v1alpha1cloudflare "github.com/prolixalias/provider-cloudflare/apis/namespaced/cloudflare/v1alpha1"
	v1alpha1cloudforce "github.com/prolixalias/provider-cloudflare/apis/namespaced/cloudforce/v1alpha1"
	v1alpha1connectivity "github.com/prolixalias/provider-cloudflare/apis/namespaced/connectivity/v1alpha1"
	v1alpha1content "github.com/prolixalias/provider-cloudflare/apis/namespaced/content/v1alpha1"
	v1alpha1custom "github.com/prolixalias/provider-cloudflare/apis/namespaced/custom/v1alpha1"
	v1alpha1d1 "github.com/prolixalias/provider-cloudflare/apis/namespaced/d1/v1alpha1"
	v1alpha1dns "github.com/prolixalias/provider-cloudflare/apis/namespaced/dns/v1alpha1"
	v1alpha1email "github.com/prolixalias/provider-cloudflare/apis/namespaced/email/v1alpha1"
	v1alpha1firewall "github.com/prolixalias/provider-cloudflare/apis/namespaced/firewall/v1alpha1"
	v1alpha1hostname "github.com/prolixalias/provider-cloudflare/apis/namespaced/hostname/v1alpha1"
	v1alpha1hyperdrive "github.com/prolixalias/provider-cloudflare/apis/namespaced/hyperdrive/v1alpha1"
	v1alpha1image "github.com/prolixalias/provider-cloudflare/apis/namespaced/image/v1alpha1"
	v1alpha1keyless "github.com/prolixalias/provider-cloudflare/apis/namespaced/keyless/v1alpha1"
	v1alpha1leaked "github.com/prolixalias/provider-cloudflare/apis/namespaced/leaked/v1alpha1"
	v1alpha1list "github.com/prolixalias/provider-cloudflare/apis/namespaced/list/v1alpha1"
	v1alpha1load "github.com/prolixalias/provider-cloudflare/apis/namespaced/load/v1alpha1"
	v1alpha1logpull "github.com/prolixalias/provider-cloudflare/apis/namespaced/logpull/v1alpha1"
	v1alpha1logpush "github.com/prolixalias/provider-cloudflare/apis/namespaced/logpush/v1alpha1"
	v1alpha1magic "github.com/prolixalias/provider-cloudflare/apis/namespaced/magic/v1alpha1"
	v1alpha1managed "github.com/prolixalias/provider-cloudflare/apis/namespaced/managed/v1alpha1"
	v1alpha1mtls "github.com/prolixalias/provider-cloudflare/apis/namespaced/mtls/v1alpha1"
	v1alpha1notification "github.com/prolixalias/provider-cloudflare/apis/namespaced/notification/v1alpha1"
	v1alpha1observatory "github.com/prolixalias/provider-cloudflare/apis/namespaced/observatory/v1alpha1"
	v1alpha1organization "github.com/prolixalias/provider-cloudflare/apis/namespaced/organization/v1alpha1"
	v1alpha1origin "github.com/prolixalias/provider-cloudflare/apis/namespaced/origin/v1alpha1"
	v1alpha1page "github.com/prolixalias/provider-cloudflare/apis/namespaced/page/v1alpha1"
	v1alpha1pages "github.com/prolixalias/provider-cloudflare/apis/namespaced/pages/v1alpha1"
	v1alpha1queue "github.com/prolixalias/provider-cloudflare/apis/namespaced/queue/v1alpha1"
	v1alpha1r2 "github.com/prolixalias/provider-cloudflare/apis/namespaced/r2/v1alpha1"
	v1alpha1rate "github.com/prolixalias/provider-cloudflare/apis/namespaced/rate/v1alpha1"
	v1alpha1regional "github.com/prolixalias/provider-cloudflare/apis/namespaced/regional/v1alpha1"
	v1alpha1registrar "github.com/prolixalias/provider-cloudflare/apis/namespaced/registrar/v1alpha1"
	v1alpha1schema "github.com/prolixalias/provider-cloudflare/apis/namespaced/schema/v1alpha1"
	v1alpha1snippet "github.com/prolixalias/provider-cloudflare/apis/namespaced/snippet/v1alpha1"
	v1alpha1spectrum "github.com/prolixalias/provider-cloudflare/apis/namespaced/spectrum/v1alpha1"
	v1alpha1sso "github.com/prolixalias/provider-cloudflare/apis/namespaced/sso/v1alpha1"
	v1alpha1stream "github.com/prolixalias/provider-cloudflare/apis/namespaced/stream/v1alpha1"
	v1alpha1tiered "github.com/prolixalias/provider-cloudflare/apis/namespaced/tiered/v1alpha1"
	v1alpha1token "github.com/prolixalias/provider-cloudflare/apis/namespaced/token/v1alpha1"
	v1alpha1total "github.com/prolixalias/provider-cloudflare/apis/namespaced/total/v1alpha1"
	v1alpha1turnstile "github.com/prolixalias/provider-cloudflare/apis/namespaced/turnstile/v1alpha1"
	v1alpha1universal "github.com/prolixalias/provider-cloudflare/apis/namespaced/universal/v1alpha1"
	v1alpha1url "github.com/prolixalias/provider-cloudflare/apis/namespaced/url/v1alpha1"
	v1alpha1user "github.com/prolixalias/provider-cloudflare/apis/namespaced/user/v1alpha1"
	v1alpha1namespaced "github.com/prolixalias/provider-cloudflare/apis/namespaced/v1alpha1"
	v1beta1 "github.com/prolixalias/provider-cloudflare/apis/namespaced/v1beta1"
	v1alpha1waiting "github.com/prolixalias/provider-cloudflare/apis/namespaced/waiting/v1alpha1"
	v1alpha1web "github.com/prolixalias/provider-cloudflare/apis/namespaced/web/v1alpha1"
	v1alpha1web3 "github.com/prolixalias/provider-cloudflare/apis/namespaced/web3/v1alpha1"
	v1alpha1worker "github.com/prolixalias/provider-cloudflare/apis/namespaced/worker/v1alpha1"
	v1alpha1workers "github.com/prolixalias/provider-cloudflare/apis/namespaced/workers/v1alpha1"
	v1alpha1zero "github.com/prolixalias/provider-cloudflare/apis/namespaced/zero/v1alpha1"
	v1alpha1zone "github.com/prolixalias/provider-cloudflare/apis/namespaced/zone/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1account.SchemeBuilder.AddToScheme,
		v1alpha1addressmap.SchemeBuilder.AddToScheme,
		v1alpha1api.SchemeBuilder.AddToScheme,
		v1alpha1argo.SchemeBuilder.AddToScheme,
		v1alpha1authenticated.SchemeBuilder.AddToScheme,
		v1alpha1bot.SchemeBuilder.AddToScheme,
		v1alpha1byo.SchemeBuilder.AddToScheme,
		v1alpha1calls.SchemeBuilder.AddToScheme,
		v1alpha1certificate.SchemeBuilder.AddToScheme,
		v1alpha1cloud.SchemeBuilder.AddToScheme,
		v1alpha1cloudflare.SchemeBuilder.AddToScheme,
		v1alpha1cloudforce.SchemeBuilder.AddToScheme,
		v1alpha1connectivity.SchemeBuilder.AddToScheme,
		v1alpha1content.SchemeBuilder.AddToScheme,
		v1alpha1custom.SchemeBuilder.AddToScheme,
		v1alpha1d1.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1email.SchemeBuilder.AddToScheme,
		v1alpha1firewall.SchemeBuilder.AddToScheme,
		v1alpha1hostname.SchemeBuilder.AddToScheme,
		v1alpha1hyperdrive.SchemeBuilder.AddToScheme,
		v1alpha1image.SchemeBuilder.AddToScheme,
		v1alpha1keyless.SchemeBuilder.AddToScheme,
		v1alpha1leaked.SchemeBuilder.AddToScheme,
		v1alpha1list.SchemeBuilder.AddToScheme,
		v1alpha1load.SchemeBuilder.AddToScheme,
		v1alpha1logpull.SchemeBuilder.AddToScheme,
		v1alpha1logpush.SchemeBuilder.AddToScheme,
		v1alpha1magic.SchemeBuilder.AddToScheme,
		v1alpha1managed.SchemeBuilder.AddToScheme,
		v1alpha1mtls.SchemeBuilder.AddToScheme,
		v1alpha1notification.SchemeBuilder.AddToScheme,
		v1alpha1observatory.SchemeBuilder.AddToScheme,
		v1alpha1organization.SchemeBuilder.AddToScheme,
		v1alpha1origin.SchemeBuilder.AddToScheme,
		v1alpha1page.SchemeBuilder.AddToScheme,
		v1alpha1pages.SchemeBuilder.AddToScheme,
		v1alpha1queue.SchemeBuilder.AddToScheme,
		v1alpha1r2.SchemeBuilder.AddToScheme,
		v1alpha1rate.SchemeBuilder.AddToScheme,
		v1alpha1regional.SchemeBuilder.AddToScheme,
		v1alpha1registrar.SchemeBuilder.AddToScheme,
		v1alpha1schema.SchemeBuilder.AddToScheme,
		v1alpha1snippet.SchemeBuilder.AddToScheme,
		v1alpha1spectrum.SchemeBuilder.AddToScheme,
		v1alpha1sso.SchemeBuilder.AddToScheme,
		v1alpha1stream.SchemeBuilder.AddToScheme,
		v1alpha1tiered.SchemeBuilder.AddToScheme,
		v1alpha1token.SchemeBuilder.AddToScheme,
		v1alpha1total.SchemeBuilder.AddToScheme,
		v1alpha1turnstile.SchemeBuilder.AddToScheme,
		v1alpha1universal.SchemeBuilder.AddToScheme,
		v1alpha1url.SchemeBuilder.AddToScheme,
		v1alpha1user.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1waiting.SchemeBuilder.AddToScheme,
		v1alpha1web.SchemeBuilder.AddToScheme,
		v1alpha1web3.SchemeBuilder.AddToScheme,
		v1alpha1worker.SchemeBuilder.AddToScheme,
		v1alpha1workers.SchemeBuilder.AddToScheme,
		v1alpha1zero.SchemeBuilder.AddToScheme,
		v1alpha1zone.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
